NAME	:= replace
CC		:= c++
CFLAGS	:= -Wall -Wextra -Werror -std=c++98

SRCS	:= main.cpp Replace.cpp
OBJS	:= $(SRCS:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(NAME)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME) *.replace

re: fclean all

.PHONY: all clean fclean re